#!/bin/bash

cd simulations;

# Run tests
python -m unittest discover . '*test*.py'

python experiment.py  \
 	--numClients 300 \
	--numServers 50 \
	--numWorkload 200 \
	--workloadModel poisson \
	--serverConcurrency 4 \
	--serviceTime 4 \
	--utilization 0.70 \
	--serviceTimeModel random.expovariate \
	--replicationFactor 3 \
	--rateInterval  20\
	--cubicC 0.000004\
	--cubicSmax 10\
	--cubicBeta 0.2\
	--hysterisisFactor 2\
	--selectionStrategy TLL \
	--shadowReadRatio 0.1 \
	--accessPattern uniform \
	--nwLatencyBase 0.25 \
	--nwLatencyMu 0.0\
	--nwLatencySigma 0.00 \
	--expPrefix TLL-seed1inter500\
	--simulationDuration 50000 \
	--seed 1 \
	--numRequests 600000\
	--logFolder logs\
	--expScenario timeVaryingServiceTimeServers\
	--demandSkew 0.0\
	--highDemandFraction 0.0\
	--slowServerFraction 0.0\
	--slowServerSlowness 0.0\
	--intervalParam 500\
	--timeVaryingDrift 3\
	--concurrencyWeight 150\
	--batchSizeModel constant\
	--batchSizeParam 1;


python experiment.py  \
 	--numClients 300 \
	--numServers 50 \
	--numWorkload 200 \
	--workloadModel poisson \
	--serverConcurrency 4 \
	--serviceTime 4 \
	--utilization 0.70 \
	--serviceTimeModel random.expovariate \
	--replicationFactor 3 \
	--rateInterval  20\
	--cubicC 0.000004\
	--cubicSmax 10\
	--cubicBeta 0.2\
	--hysterisisFactor 2\
	--selectionStrategy TLL \
	--shadowReadRatio 0.1 \
	--accessPattern uniform \
	--nwLatencyBase 0.25 \
	--nwLatencyMu 0.0\
	--nwLatencySigma 0.00 \
	--expPrefix TLL-seed16inter500\
	--simulationDuration 50000 \
	--seed 16 \
	--numRequests 600000\
	--logFolder logs\
	--expScenario timeVaryingServiceTimeServers\
	--demandSkew 0.0\
	--highDemandFraction 0.0\
	--slowServerFraction 0.0\
	--slowServerSlowness 0.0\
	--intervalParam 500\
	--timeVaryingDrift 3\
	--concurrencyWeight 150\
	--batchSizeModel constant\
	--batchSizeParam 1;



python experiment.py  \
 	--numClients 300 \
	--numServers 50 \
	--numWorkload 200 \
	--workloadModel poisson \
	--serverConcurrency 4 \
	--serviceTime 4 \
	--utilization 0.70 \
	--serviceTimeModel random.expovariate \
	--replicationFactor 3 \
	--rateInterval  20\
	--cubicC 0.000004\
	--cubicSmax 10\
	--cubicBeta 0.2\
	--hysterisisFactor 2\
	--selectionStrategy TLL \
	--shadowReadRatio 0.1 \
	--accessPattern uniform \
	--nwLatencyBase 0.25 \
	--nwLatencyMu 0.0\
	--nwLatencySigma 0.00 \
	--expPrefix TLL-seed128inter500\
	--simulationDuration 50000 \
	--seed 128 \
	--numRequests 600000\
	--logFolder logs\
	--expScenario timeVaryingServiceTimeServers\
	--demandSkew 0.0\
	--highDemandFraction 0.0\
	--slowServerFraction 0.0\
	--slowServerSlowness 0.0\
	--intervalParam 500\
	--timeVaryingDrift 3\
	--concurrencyWeight 150\
	--batchSizeModel constant\
	--batchSizeParam 1;




python experiment.py  \
 	--numClients 300 \
	--numServers 50 \
	--numWorkload 200 \
	--workloadModel poisson \
	--serverConcurrency 4 \
	--serviceTime 4 \
	--utilization 0.70 \
	--serviceTimeModel random.expovariate \
	--replicationFactor 3 \
	--rateInterval  20\
	--cubicC 0.000004\
	--cubicSmax 10\
	--cubicBeta 0.2\
	--hysterisisFactor 2\
	--selectionStrategy TLL \
	--shadowReadRatio 0.1 \
	--accessPattern uniform \
	--nwLatencyBase 0.25 \
	--nwLatencyMu 0.0\
	--nwLatencySigma 0.00 \
	--expPrefix TLL-seed1024inter500\
	--simulationDuration 50000 \
	--seed 1024 \
	--numRequests 600000\
	--logFolder logs\
	--expScenario timeVaryingServiceTimeServers\
	--demandSkew 0.0\
	--highDemandFraction 0.0\
	--slowServerFraction 0.0\
	--slowServerSlowness 0.0\
	--intervalParam 500\
	--timeVaryingDrift 3\
	--concurrencyWeight 150\
	--batchSizeModel constant\
	--batchSizeParam 1;




python experiment.py  \
 	--numClients 300 \
	--numServers 50 \
	--numWorkload 200 \
	--workloadModel poisson \
	--serverConcurrency 4 \
	--serviceTime 4 \
	--utilization 0.70 \
	--serviceTimeModel random.expovariate \
	--replicationFactor 3 \
	--rateInterval  20\
	--cubicC 0.000004\
	--cubicSmax 10\
	--cubicBeta 0.2\
	--hysterisisFactor 2\
	--selectionStrategy TLL \
	--shadowReadRatio 0.1 \
	--accessPattern uniform \
	--nwLatencyBase 0.25 \
	--nwLatencyMu 0.0\
	--nwLatencySigma 0.00 \
	--expPrefix TLL-seed20480inter500\
	--simulationDuration 50000 \
	--seed 20480 \
	--numRequests 600000\
	--logFolder logs\
	--expScenario timeVaryingServiceTimeServers\
	--demandSkew 0.0\
	--highDemandFraction 0.0\
	--slowServerFraction 0.0\
	--slowServerSlowness 0.0\
	--intervalParam 500\
	--timeVaryingDrift 3\
	--concurrencyWeight 150\
	--batchSizeModel constant\
	--batchSizeParam 1;




cd ..
cd plotting;
# Rscript timeseries.r primary;
# Rscript timeseries.r rp;
# Rscript timeseries.r clairvoyant;
# Rscript timeseries.r clairvoyant2;
# Rscript timeseries.r pending;
# Rscript timeseries.r pendingXserviceTime;
# Rscript timeseries.r oracle;

Rscript timeseries.r TLL-seed1inter500;
Rscript timeseries.r TLL-seed16inter500;
Rscript timeseries.r TLL-seed128inter500;
Rscript timeseries.r TLL-seed1024inter500;
Rscript timeseries.r TLL-seed20480inter500;
cd ..
